theme: minima
title: The Justonic Dialogues
author: Just
description: A personal and philosophical journey into our relationship with AI.

plugins:
  - jekyll-feed
  - jekyll-sitemap 
  - jekyll-seo-tag

